using System.Collections.Generic;
using System.Reflection;
using RimWorld;
using Verse;

namespace UniqueWeaponsUnbound
{
    // Mutates a weapon Thing in place: adds/removes traits (delegating
    // ability-comp wiring to EquippableAbilityUtility), sets cosmetic
    // properties (name, color, texture), and spawns refunded resources. Def
    // conversion (base↔unique) lives in WeaponDefConversion; ingredient
    // gathering and reservation for a customization job lives in
    // HaulPlanning.IngredientReservation.
    public static class WeaponModificationUtility
    {
        // Reflection fields for CompUniqueWeapon private members. Resolved once
        // at static-init; verified by Initialize() so a RimWorld API rename
        // surfaces as a startup error instead of a silent no-op on every
        // SetName/SetColor/AddTrait/RemoveTrait at runtime.
        internal static readonly FieldInfo CompNameField = typeof(CompUniqueWeapon)
            .GetField("name", BindingFlags.NonPublic | BindingFlags.Instance);

        internal static readonly FieldInfo CompColorField = typeof(CompUniqueWeapon)
            .GetField("color", BindingFlags.NonPublic | BindingFlags.Instance);

        internal static readonly FieldInfo IgnoreAccuracyField = typeof(CompUniqueWeapon)
            .GetField("ignoreAccuracyMaluses", BindingFlags.NonPublic | BindingFlags.Instance);

        // Verb caches burstShot{Speed,Count}Multiplier-folded results on first
        // access of TicksBetweenBurstShots / BurstShotCount and never
        // invalidates them. The fields aren't Scribed, so reloading the save
        // resets them to null and the next access recomputes — which is why
        // burst-trait stat changes don't take effect until reload. Cleared
        // alongside the IgnoreAccuracyField scrub in AddTrait/RemoveTrait/
        // ClearAutoGeneratedUniqueState.
        internal static readonly FieldInfo VerbBurstTicksField = typeof(Verb)
            .GetField("cachedTicksBetweenBurstShots", BindingFlags.NonPublic | BindingFlags.Instance);

        internal static readonly FieldInfo VerbBurstCountField = typeof(Verb)
            .GetField("cachedBurstShotCount", BindingFlags.NonPublic | BindingFlags.Instance);

        // Verifies that every cached CompUniqueWeapon FieldInfo resolved.
        // Should be called during StaticConstructorOnStartup so a RimWorld API
        // rename surfaces as a startup error rather than a silent no-op on
        // every later SetName/SetColor/AddTrait/RemoveTrait. Pure diagnostic —
        // no state is built here; the FieldInfos are resolved at class-load
        // time by the field initializers above.
        public static void VerifyReflection()
        {
            if (CompNameField == null)
                Log.Error("[Unique Weapons Unbound] CompUniqueWeapon.name field not found via reflection; "
                    + "weapon renaming will silently no-op. RimWorld API may have changed.");
            if (CompColorField == null)
                Log.Error("[Unique Weapons Unbound] CompUniqueWeapon.color field not found via reflection; "
                    + "weapon color changes will silently no-op. RimWorld API may have changed.");
            if (IgnoreAccuracyField == null)
                Log.Error("[Unique Weapons Unbound] CompUniqueWeapon.ignoreAccuracyMaluses field not found via reflection; "
                    + "accuracy-malus cache won't be invalidated after trait changes. RimWorld API may have changed.");
            if (VerbBurstTicksField == null)
                Log.Error("[Unique Weapons Unbound] Verb.cachedTicksBetweenBurstShots field not found via reflection; "
                    + "burst-speed trait changes won't take effect until save reload. RimWorld API may have changed.");
            if (VerbBurstCountField == null)
                Log.Error("[Unique Weapons Unbound] Verb.cachedBurstShotCount field not found via reflection; "
                    + "burst-count trait changes won't take effect until save reload. RimWorld API may have changed.");
        }

        // Clears the per-Verb lazy caches that fold burstShotSpeedMultiplier
        // and burstShotCountMultiplier from the weapon's trait list. Vanilla
        // populates these on first access and never invalidates them — and they
        // aren't Scribed, so the only thing that resets them is a save reload
        // (private fields default back to null on the freshly-loaded Verb
        // instance). Without this scrub, adding or removing a burst-affecting
        // trait leaves the weapon's burst behavior frozen at the pre-change
        // value until the player reloads.
        //
        // Verb instances live on the weapon's own CompEquippable.VerbTracker,
        // not the equipping pawn, so the unequip/re-equip cycle our acquire and
        // recovery phases drive doesn't help — the same instances persist
        // across it, and Verb.Reset() (which Notify_PickedUp triggers) only
        // touches per-shot state, not the burst caches.
        //
        // Safe on non-unique weapons (CompEquippable absent → no-op) and on
        // weapons whose Verbs haven't been accessed yet (fields already null).
        internal static void InvalidateVerbBurstCaches(Thing weapon)
        {
            if (VerbBurstTicksField == null && VerbBurstCountField == null)
                return;
            CompEquippable comp = (weapon as ThingWithComps)?.GetComp<CompEquippable>();
            if (comp == null)
                return;
            List<Verb> verbs = comp.AllVerbs;
            if (verbs == null)
                return;
            for (int i = 0; i < verbs.Count; i++)
            {
                Verb verb = verbs[i];
                if (verb == null)
                    continue;
                VerbBurstTicksField?.SetValue(verb, null);
                VerbBurstCountField?.SetValue(verb, null);
            }
        }

        // Invalidates every lazily-cached fold of the trait list after that
        // list changes: the comp's ignoreAccuracyMaluses memo (vanilla Setup()
        // never resets it, so accuracy behaviour stays frozen at first read
        // until the comp is recreated by def conversion or save/load) and the
        // per-Verb burst caches (see InvalidateVerbBurstCaches). Every trait
        // mutation path — AddTrait, RemoveTrait, ClearAutoGeneratedUniqueState,
        // StampTraits — funnels through here so a newly discovered vanilla
        // cache gets invalidated in one place.
        internal static void InvalidateTraitCaches(Thing weapon, CompUniqueWeapon comp)
        {
            IgnoreAccuracyField?.SetValue(comp, null);
            InvalidateVerbBurstCaches(weapon);
        }

        public static void AddTrait(Thing weapon, WeaponTraitDef trait)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp == null)
            {
                Log.Error("[Unique Weapons Unbound] AddTrait: weapon has no CompUniqueWeapon.");
                return;
            }

            comp.AddTrait(trait);

            InvalidateTraitCaches(weapon, comp);

            // Mirror RemoveTrait: if any earlier customization, auto-gen, or
            // mod-side handling left a stale Ability cached on the equippable-
            // ability comp, vanilla Setup() won't rebuild it — it only reassigns
            // props, and the lazy AbilityForReading getter keeps returning the
            // cached instance. Reset so the getter constructs a fresh Ability
            // matching the new abilityProps. Two ability traits rarely coexist
            // thanks to exclusionTags <li>Ability</li>, but the stale-cache state
            // can still be reached via a partially-healed save or non-vanilla
            // trait wiring.
            if (trait.abilityProps != null)
                EquippableAbilityUtility.ResetState(weapon);

            EquippableAbilityUtility.SetupAndPreserveCharges(weapon, comp);
        }

        public static void RemoveTrait(Thing weapon, WeaponTraitDef trait)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp == null)
            {
                Log.Error("[Unique Weapons Unbound] RemoveTrait: weapon has no CompUniqueWeapon.");
                return;
            }

            comp.TraitsListForReading.Remove(trait);

            InvalidateTraitCaches(weapon, comp);

            // Vanilla CompUniqueWeapon.Setup() only assigns props for traits that
            // have abilityProps; it never clears them when an ability-granting trait
            // is removed, and never resets the cached Ability instance. Without this
            // scrub, an equipped pawn keeps the removed trait's gizmo (e.g. the
            // grenade launcher's launch+reload command) the next time the weapon is
            // re-equipped — even if the trait was swapped for one with different
            // abilityProps, because the lazy AbilityForReading getter only rebuilds
            // when its cache is null.
            if (trait.abilityProps != null)
                EquippableAbilityUtility.ResetState(weapon);

            EquippableAbilityUtility.SetupAndPreserveCharges(weapon, comp);
        }

        // Scrubs the random state left behind by CompUniqueWeapon.PostPostMake
        // on a freshly minted unique weapon: the auto-rolled trait list, the
        // generated name and color, the lazy ignoreAccuracyMaluses cache, and
        // the equippable-ability comp's stale props + cached Ability instance.
        // Called by WeaponDefConversion right after ThingMaker.MakeThing on a
        // unique-weapon def so the customization pipeline starts from a clean
        // slate.
        //
        // Without the ability-comp scrub, an ability trait randomly rolled by
        // InitializeTraits (e.g. SmokeLauncher → LaunchSmokeShell) wires up
        // CompEquippableAbilityReloadable.props and lazily constructs its
        // Ability. Clearing the trait list afterwards doesn't undo that wiring
        // — vanilla Setup() only assigns props for traits currently in the
        // list, never clears them — and the cached Ability is even deep-scribed
        // across save/load, so the phantom gizmo persists.
        //
        // No-op on non-unique target defs (no CompUniqueWeapon).
        internal static void ClearAutoGeneratedUniqueState(Thing weapon)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp == null)
                return;

            comp.TraitsListForReading.Clear();
            CompNameField?.SetValue(comp, null);
            CompColorField?.SetValue(comp, null);
            InvalidateTraitCaches(weapon, comp);
            EquippableAbilityUtility.ResetState(weapon);
        }

        // Wholesale trait-list replacement for a prospective weapon Thing —
        // the customization dialog's preview — leaving comp and verb cache
        // state as if the same list had been reached through AddTrait/
        // RemoveTrait. The job-flow halves of those entry points (costs,
        // refunds) don't apply to a display-only thing and are skipped;
        // charge preservation is instead approximated by mirroring
        // chargeSource's remaining charges when the staged set keeps its
        // ability trait (see MirrorChargesForKeptTrait), so a kept launcher
        // trait previews its real count rather than a free refill.
        //
        // The ability comp is re-wired only when the stamp changes which
        // abilityProps the trait list carries. Wiring constructs the vanilla
        // Ability eagerly — Notify_PropsChanged seeds max charges from the
        // trait's abilityProps, and the AbilityDefs authored for weapon
        // traits carry no charges of their own, so a lazily-built Ability
        // would report UsesCharges == false and the info card would drop its
        // charges row — and each construction draws a global ability id.
        // Gating on the ability projection keeps that draw off the common
        // path (color/texture/non-ability trait toggles) and bounds it to
        // explicit ability-trait changes: the same order of global-state
        // noise as the preview's per-def-change thing id, accepted for the
        // same reason. The re-wire runs under Rand.PushState because stamps
        // happen at GUI time, off the synchronized tick — Ability/verb
        // construction isn't known to roll the global Rand, but the guard
        // makes that a non-assumption.
        public static void StampTraits(
            Thing weapon, List<WeaponTraitDef> desiredTraits, Thing chargeSource = null)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp == null)
                return;

            List<WeaponTraitDef> traits = comp.TraitsListForReading;
            bool rewireAbility = !SameAbilityProjection(traits, desiredTraits);
            traits.Clear();
            traits.AddRange(desiredTraits);

            InvalidateTraitCaches(weapon, comp);

            if (rewireAbility)
            {
                Rand.PushState();
                try
                {
                    EquippableAbilityUtility.ResetState(weapon);
                    EquippableAbilityUtility.SetupAndPreserveCharges(weapon, comp);
                    EquippableAbilityUtility.MirrorChargesForKeptTrait(chargeSource, weapon);
                }
                finally
                {
                    Rand.PopState();
                }
            }
        }

        // True when both trait lists carry the same abilityProps sequence —
        // the only projection of a trait list the equippable-ability comp is
        // wired from. Reference equality per element is right: abilityProps
        // instances live on the trait defs themselves. Order-sensitive, like
        // vanilla Setup()'s last-wins iteration; a same-set reorder at worst
        // re-wires to an identical state.
        internal static bool SameAbilityProjection(
            List<WeaponTraitDef> current, List<WeaponTraitDef> desired)
        {
            int ic = 0;
            int id = 0;
            while (true)
            {
                while (ic < current.Count && current[ic].abilityProps == null)
                    ic++;
                while (id < desired.Count && desired[id].abilityProps == null)
                    id++;
                if (ic >= current.Count || id >= desired.Count)
                    return ic >= current.Count && id >= desired.Count;
                if (current[ic].abilityProps != desired[id].abilityProps)
                    return false;
                ic++;
                id++;
            }
        }

        public static void SetName(Thing weapon, string name)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp != null && CompNameField != null)
                CompNameField.SetValue(comp, name);

            // Keep CompArt.Title in sync for inspection dialogs
            CompArt artComp = weapon.TryGetComp<CompArt>();
            if (artComp != null && !string.IsNullOrEmpty(name))
                artComp.Title = name;
        }

        public static void SetColor(Thing weapon, ColorDef color)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp != null && CompColorField != null)
            {
                CompColorField.SetValue(comp, color);
                weapon.Notify_ColorChanged();
            }
        }

        public static void SetTextureIndex(Thing weapon, int index)
        {
            weapon.overrideGraphicIndex = index;
        }

        // Spawns resources near a position (e.g. the workbench). Used to refund
        // resources when removing traits.
        public static void SpawnResourcesNear(
            Map map, IntVec3 center, List<ThingDefCountClass> resources)
        {
            if (resources == null || resources.Count == 0)
                return;

            foreach (ThingDefCountClass resource in resources)
            {
                if (resource.count <= 0)
                    continue;

                Thing thing = ThingMaker.MakeThing(resource.thingDef);
                thing.stackCount = resource.count;
                GenPlace.TryPlaceThing(thing, center, map, ThingPlaceMode.Near);
            }
        }

    }
}
