#!/usr/bin/env python3
# Validates mod translation files against the English source of truth and the
# checked-in expectations sidecar. Deterministic companion to the
# .claude/skills/translate flow: anything this script can prove is never
# re-derived by an agent.
#
# The DefInjected expected set comes from Scripts/expected-injections.json —
# a dump of every legal injection point the LIVE game sees for this mod,
# generated by Scripts/refresh-translation-expectations.py driving the
# L10nProbe dev mod (which calls the game's own walker,
# Verse.DefInjectionUtility.ForEachPossibleDefInjection). That is the only
# way to see translatable text this script's def-XML scan structurally
# cannot: fields inherited from VANILLA parents (melee tools lists,
# FactionBase's messageDefendersAttacking, InjuryBase's labelNounPretty) and
# C# field DEFAULTS never written in any XML (the ability comp's chargeNoun /
# cooldownGerund). Unknown gap classes are impossible by structure: any
# defName in Defs/ the sidecar has never seen fails this script until the
# sidecar is regenerated, and the regen sees everything the game sees.
#
# Checks per non-English language:
#   Keyed:       missing/extra keys, argument-placeholder mismatches, stale EN
#                comments (grammar constructs like {PAWN_gender ? a : b : c} are
#                language-specific and deliberately not compared - see below)
#   DefInjected: folder names are sidecar def types, every key is a legal
#                injection point (directly, via the sidecar's normalized
#                alias, or as element N of a collection entry), placeholder
#                and stale-EN-comment checks against the sidecar's English,
#                completeness of the sidecar's required subset
#   All files:   well-formed XML, <LanguageData> root, UTF-8 no BOM, LF line
#                endings, no tabs, final newline (hygiene -> warnings)
# Plus, language-independent:
#   Sidecar:     generated with the right DLC set (MayRequire-gated defs
#                vanish from a dump made without their DLC), fresh against
#                Defs/ (defNames and label/description English text)
#
# Staleness relies on the EN-comment convention: every translated entry carries
# the English source directly above it, e.g.
#   <!-- EN: Reset to defaults -->
#   <UMW_ResetToDefaults>...</UMW_ResetToDefaults>
# A missing EN comment is a warning; an EN comment that no longer matches the
# current English text is an error (the translation is stale).
#
# Exit code: 1 if any errors (or, with --strict, any warnings), else 0.

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

PLACEHOLDER_RE = re.compile(r"\{[^{}]*\}")
EN_COMMENT_RE = re.compile(r"^\s*EN:\s?(.*)$", re.DOTALL)

# A {...} span is one of two different things, and only one of them is an interface
# contract with the C# call site.
#
#   argument placeholder   {0}, {1}, {PAWN_labelShort}
#       Supplied by the caller. A language that drops or invents one is broken, so
#       these must match English exactly.
#
#   grammar construct      {PAWN_gender ? é : ée : é(e)}, {0_gender ? un : une : un(e)}
#       Resolved by GrammarResolverSimple from an argument's gender, and inflecting
#       languages need them where uninflected English does not. French Core writes
#       Cut.deathMessage as "{0} a été taillad{PAWN_gender ? é : ée : é(e)} à mort."
#       against an English "{0} has been cut to death." (HealthUtility passes both
#       pawn.LabelShortCap and pawn.Named("PAWN") precisely so this resolves.)
#       Comparing these across languages would forbid correct translations.
#
# So grammar constructs are excluded before comparing. This does not weaken the
# argument check: a construct references its subject as "PAWN_gender", never as a
# bare "{0}", so a translation that dropped a real argument still fails.
GRAMMAR_CONSTRUCT_RE = re.compile(r"\{[^{}]*\?[^{}]*\}")

# ...with one exception, and it is the reason this is not a plain exclusion.
# _numCase is the only ?-construct that CONSUMES AND PRINTS its argument
# (decompile-verified, Verse.LanguageWorker.ResolveNumCase: it returns
# `number + " " + form`, where every other construct returns only a form).
# Numeral-agreement languages therefore replace the bare placeholder with it
# rather than writing both: Core ru renders "{0} days" as
# "{0_numCase ? день : дня : дней}" — writing "{0} {0_numCase ...}" would
# print the number twice. Rewriting it back to its bare placeholder before
# the comparison keeps the argument contract enforced (drop argument 0
# entirely and it still fails) without forbidding the correct Russian.
NUM_CASE_RE = re.compile(r"\{([^{}?]*?)_numCase\s*\?[^{}]*\}")

# Fields whose entries legitimately vary per language (RimWorld's
# [TranslationCanChangeCount]-style matching tokens): exempt from the
# cross-language parity check, keyed on the final path segment.
# UWU: labelKeywords ([TranslationCanChangeCount]) are matching tokens whose
# count and presence legitimately differ per language — see SKILL.md's
# labelKeywords section (requireAllKeywords rules must NOT be injected; only
# keywords that can genuinely match should be added). The sidecar's
# fullListAllowed flag could eventually subsume it.
PARITY_EXEMPT_FIELDS = {"labelKeywords"}

# DLCs the sidecar must have been generated with: a dump made without one
# silently omits everything that DLC gates. Derived from About/About.xml's
# modDependencies (Odyssey is a hard dependency — without it the mod does not
# load at all) plus MayRequire= usage in Defs/, of which this repo has none:
# UWU_Blood is deliberately ungated so its DefInjected entries always resolve
# (see 1.6/Defs/TraitCostRuleDefs/TraitCostRules.xml), and the Alpha Armoury
# rules are still TODOs. So Odyssey alone.
REQUIRED_DLCS = {"Odyssey"}


# Def XML may declare a def via a subclass the game rolls into a base-type
# database — the probe's walker (the game's own) then dumps those defs under
# the base type, and DefInjected translations legally target that base-type
# folder. Map each subclass element tag seen in this repo's Defs/ to the def
# type the dump actually uses. Empty here today; ArchotechAndroidHardware's
# copy carries the first real entry (VREA's AndroidGeneDef -> GeneDef). Note
# this repo's own UniqueWeaponsUnbound.TraitCostRuleDef needs NO alias: def
# types a mod itself defines dump under their namespace-qualified name,
# matching the XML tag.
DEF_TYPE_ALIASES = {}


def norm(text):
    # The game decodes literal "\n" escapes in def XML text at load, so the
    # sidecar (dumped game-side) holds real newlines where the XML holds two
    # characters; decode before collapsing whitespace or every multi-paragraph
    # description reads as drifted.
    return re.sub(r"\s+", " ", (text or "").replace("\\n", "\n").strip())


def placeholders(text):
    text = NUM_CASE_RE.sub(r"{\1}", text or "")
    return set(PLACEHOLDER_RE.findall(GRAMMAR_CONSTRUCT_RE.sub("", text)))


def parse_with_comments(path):
    # Returns (root, entries) where entries is [(key, text, en_comment)].
    # The EN comment for an entry is the nearest preceding EN: comment that
    # appears after the previous element (section headers are skipped).
    builder = ET.TreeBuilder(insert_comments=True)
    root = ET.parse(path, parser=ET.XMLParser(target=builder)).getroot()
    entries = []
    pending_en = None
    for node in root:
        if node.tag is ET.Comment:
            m = EN_COMMENT_RE.match(node.text or "")
            if m:
                pending_en = m.group(1)
        else:
            entries.append((node.tag, node, pending_en))
            pending_en = None
    return root, entries


def flatten_entry(elem):
    # A Keyed/DefInjected entry is either a single text value or a list of <li>.
    kids = list(elem)
    if kids:
        return [li.text or "" for li in kids]
    return elem.text or ""


class Report:
    def __init__(self):
        self.errors = []
        self.warnings = []

    def error(self, path, msg):
        self.errors.append(f"{path}: {msg}")

    def warn(self, path, msg):
        self.warnings.append(f"{path}: {msg}")


def check_hygiene(path, report):
    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        report.error(path, "UTF-8 BOM present")
    if b"\r" in raw:
        report.warn(path, "CRLF line endings (repo convention is LF)")
    if b"\t" in raw:
        report.warn(path, "tab indentation (repo convention is 2 spaces)")
    if raw and not raw.endswith(b"\n"):
        report.warn(path, "missing final newline")


def load_language_xml(path, report):
    check_hygiene(path, report)
    try:
        root, entries = parse_with_comments(path)
    except ET.ParseError as e:
        report.error(path, f"XML parse error: {e}")
        return None
    if root.tag != "LanguageData":
        report.error(path, f"root element is <{root.tag}>, expected <LanguageData>")
        return None
    return entries


def collect_keyed(lang_dir, report):
    # key -> (text, en_comment, path)
    keyed = {}
    for path in sorted((lang_dir / "Keyed").glob("**/*.xml")) if (lang_dir / "Keyed").is_dir() else []:
        entries = load_language_xml(path, report)
        for key, elem, en in entries or []:
            if key in keyed:
                report.error(path, f"duplicate key <{key}> (also in {keyed[key][2].name})")
            keyed[key] = (flatten_entry(elem), en, path)
    return keyed


def def_is_active(elem, active_packages):
    # A def whose root node is MayRequire-gated on a package that was not
    # active during the probe boot never loaded there, so it is legitimately
    # absent from the sidecar and outside the l10n surface (e.g.
    # BetterTradersGuild's Biotech-gated ScenPartDef, where this fix
    # originated). MayRequire = ALL listed packages must be active;
    # MayRequireAnyOf = any.
    may_require = elem.get("MayRequire")
    if may_require:
        ids = {p.strip().lower() for p in may_require.split(",") if p.strip()}
        if not ids <= active_packages:
            return False
    any_of = elem.get("MayRequireAnyOf")
    if any_of:
        ids = {p.strip().lower() for p in any_of.split(",") if p.strip()}
        if ids and not ids & active_packages:
            return False
    return True


def collect_defs(defs_dirs, active_packages):
    # tag -> {defName -> element}. Abstract parents (Name=, no defName) are
    # not collected: they are not injection targets themselves. Defs gated on
    # packages inactive during the probe boot are skipped (see def_is_active).
    defs = {}
    for defs_dir in defs_dirs:
        for path in sorted(defs_dir.glob("**/*.xml")):
            try:
                root = ET.parse(path).getroot()
            except ET.ParseError:
                continue
            if root.tag != "Defs":
                continue
            for elem in root:
                if elem.tag is ET.Comment:
                    continue
                def_name = elem.findtext("defName")
                if def_name and def_is_active(elem, active_packages):
                    def_type = DEF_TYPE_ALIASES.get(elem.tag, elem.tag)
                    defs.setdefault(def_type, {})[def_name] = elem
    return defs


class Sidecar:
    # Scripts/expected-injections.json, indexed for lookups. Every entry is a
    # legal injection point; entries with required=true are what the in-game
    # report would list as missing and form the per-language completeness
    # demand. Keys are suggestedPath (handle form); an entry carries
    # "normalized" (index form) when it differs, and translation files may
    # use either — the game dedups by normalizedPath. A collection is ONE
    # entry at its path carrying all English elements; languages may
    # translate it as a full <li> list at that path or element-wise at
    # path.N.
    def __init__(self, data):
        self.meta = data.get("meta", {})
        self.entries = data["defInjections"]  # def_type -> key -> entry
        self.canon = {}       # def_type -> spelling -> canonical key
        self.def_names = {}   # def_type -> set of defNames seen
        for dt, entries in self.entries.items():
            spell = self.canon.setdefault(dt, {})
            names = self.def_names.setdefault(dt, set())
            for key, entry in entries.items():
                spell[key] = key
                if "normalized" in entry:
                    spell[entry["normalized"]] = key
                names.add(key.split(".")[0])

    @property
    def def_types(self):
        return set(self.entries)

    @property
    def active_packages(self):
        # Lowercased packageIds active during the probe boot: Core plus each
        # active DLC (ludeon.rimworld.<dlc>), plus meta.activeMods when the
        # refresh script recorded it (older sidecars predate that field).
        pkgs = {"ludeon.rimworld"}
        for dlc in self.meta.get("activeDlcs", []):
            if dlc != "Core":
                pkgs.add(f"ludeon.rimworld.{dlc.lower()}")
        pkgs.update(m.lower() for m in self.meta.get("activeMods", []))
        return pkgs

    def lookup(self, def_type, key):
        # Resolve a translated key to (canonical_key, element_index):
        # element_index is None for the entry itself (scalar, or a full-list
        # translation of a collection), an int for a path.N element of a
        # collection. Returns None for keys that are not legal injection
        # points.
        spell = self.canon.get(def_type, {})
        if key in spell:
            return spell[key], None
        head, _, tail = key.rpartition(".")
        if tail.isdigit() and head in spell:
            canonical = spell[head]
            entry = self.entries[def_type][canonical]
            if entry.get("isCollection") and int(tail) < len(entry["english"]):
                return canonical, int(tail)
        return None

    def required(self, def_type):
        return {k: e for k, e in self.entries.get(def_type, {}).items()
                if e.get("required")}


def load_sidecar(root, report):
    path = root / "Scripts" / "expected-injections.json"
    if not path.is_file():
        print(f"{path} is missing — generate it with "
              f"Scripts/refresh-translation-expectations.py", file=sys.stderr)
        return None
    sidecar = Sidecar(json.loads(path.read_text(encoding="utf-8")))
    missing_dlcs = REQUIRED_DLCS - set(sidecar.meta.get("activeDlcs", []))
    if missing_dlcs:
        report.error(path, f"sidecar was generated without "
                           f"{sorted(missing_dlcs)} active — MayRequire-gated "
                           f"defs are absent from it; rerun the probe with "
                           f"the right DLC set")
    return sidecar


def check_sidecar_freshness(defs, sidecar, report):
    # The rule that makes stale expectations loud: every def carrying a
    # label/description in XML must appear in the sidecar, so new or edited
    # translatable content forces a regen, and the regen sees everything the
    # game sees. The probe dumps only defs with at least one possible
    # injection point, so defs with NO translatable text in XML (most
    # DutyDefs, PrefabDefs, ...) are legitimately absent and tolerated —
    # whether or not their def type has other entries.
    label = "[Scripts/expected-injections.json]"
    stale = (f"expectations stale — rerun "
             f"Scripts/refresh-translation-expectations.py")
    for def_type, by_name in sorted(defs.items()):
        if def_type not in sidecar.def_types:
            for def_name, elem in sorted(by_name.items()):
                if elem.find("label") is not None \
                        or elem.find("description") is not None:
                    report.error(label, f"{def_type} {def_name} has a label/"
                                        f"description but its def type has no "
                                        f"sidecar entries; {stale}")
            continue
        # English drift: a label/description edited in XML without a regen.
        for def_name, elem in sorted(by_name.items()):
            for field in ("label", "description"):
                node = elem.find(field)
                if node is None:
                    continue
                entry = sidecar.entries[def_type].get(f"{def_name}.{field}")
                if entry is None:
                    report.error(label, f"{def_type} {def_name}.{field} is in "
                                        f"the def XML but not the sidecar; "
                                        f"{stale}")
                elif norm(entry["english"]) != norm(node.text):
                    report.error(label, f"{def_type} {def_name}.{field} "
                                        f"English differs between def XML and "
                                        f"sidecar; {stale}")


def check_language(lang_dir, english_keyed, sidecar, report):
    # Returns {def_type: set(canonical keys/elements)} actually translated in
    # this language, for the cross-language parity check in main(). Element
    # translations are recorded as "<canonical collection key>.<index>".
    lang = lang_dir.name

    # --- Keyed ---
    keyed = collect_keyed(lang_dir, report)
    label = f"[{lang}/Keyed]"
    for key in sorted(set(english_keyed) - set(keyed)):
        report.error(label, f"missing key <{key}>")
    for key, (_, _, path) in sorted(keyed.items()):
        if key not in english_keyed:
            report.error(path, f"unknown key <{key}> (not in English)")
            continue
        text, en, _ = keyed[key]
        en_text = english_keyed[key][0]
        if isinstance(text, str) and isinstance(en_text, str):
            if placeholders(text) != placeholders(en_text):
                report.error(path, f"<{key}> placeholders {sorted(placeholders(text))} "
                                   f"!= English {sorted(placeholders(en_text))}")
        if en is None:
            report.warn(path, f"<{key}> has no EN: comment")
        elif isinstance(en_text, str) and norm(en) != norm(en_text):
            report.error(path, f"<{key}> is STALE: EN comment does not match current "
                               f"English text")

    # --- DefInjected ---
    found = {}       # def_type -> canonical keys / "<key>.<idx>" elements
    full_lists = {}  # def_type -> canonical collection keys translated as full lists
    inj_root = lang_dir / "DefInjected"
    folders = sorted(p for p in inj_root.iterdir() if p.is_dir()) \
        if inj_root.is_dir() else []
    for folder in folders:
        def_type = folder.name
        if def_type not in sidecar.def_types:
            report.error(folder, f"folder does not match any def type in the "
                                 f"sidecar (expected one of: "
                                 f"{', '.join(sorted(sidecar.def_types))})")
            continue
        for path in sorted(folder.glob("**/*.xml")):
            entries = load_language_xml(path, report)
            for key, elem, en in entries or []:
                resolved = sidecar.lookup(def_type, key)
                if resolved is None:
                    report.error(path, f"<{key}>: not a legal injection point "
                                       f"per the sidecar (typo, or "
                                       f"expectations stale — rerun "
                                       f"Scripts/refresh-translation-"
                                       f"expectations.py)")
                    continue
                canonical, idx = resolved
                entry = sidecar.entries[def_type][canonical]
                text = flatten_entry(elem)
                if idx is not None:
                    found.setdefault(def_type, set()).add(f"{canonical}.{idx}")
                    en_text = entry["english"][idx]
                elif entry.get("isCollection"):
                    found.setdefault(def_type, set()).add(canonical)
                    full_lists.setdefault(def_type, set()).add(canonical)
                    en_text = None
                    if not isinstance(text, list):
                        report.error(path, f"<{key}> is a collection but the "
                                           f"translation is not a <li> list")
                    elif not entry.get("fullListAllowed") \
                            and len(text) != len(entry["english"]):
                        report.error(path, f"<{key}> full-list translation has "
                                           f"{len(text)} elements, English has "
                                           f"{len(entry['english'])}")
                else:
                    found.setdefault(def_type, set()).add(canonical)
                    en_text = entry["english"]
                if isinstance(text, str) and en_text is not None:
                    if placeholders(text) != placeholders(en_text):
                        report.error(path, f"<{key}> placeholders {sorted(placeholders(text))} "
                                           f"!= English {sorted(placeholders(en_text))}")
                if en is None:
                    report.warn(path, f"<{key}> has no EN: comment")
                elif en_text is not None and norm(en) != norm(en_text):
                    report.error(path, f"<{key}> is STALE: EN comment does not match "
                                       f"current English source")

    # Completeness: every required sidecar entry must be translated. A
    # required collection is satisfied by a full-list translation or by all
    # of its elements. An entire def type nobody has started translating
    # lands here too — the old per-folder walk silently skipped those (how
    # the WeaponCategoryDef labels shipped missing in all languages).
    for def_type in sorted(sidecar.def_types):
        got = found.get(def_type, set())
        for key, entry in sorted(sidecar.required(def_type).items()):
            if not entry.get("isCollection"):
                if key not in got:
                    report.error(f"[{lang}/DefInjected/{def_type}]",
                                 f"missing <{key}> (EN: {entry['english']!r})")
            elif key not in full_lists.get(def_type, set()):
                for i, en_text in enumerate(entry["english"]):
                    if f"{key}.{i}" not in got:
                        report.error(f"[{lang}/DefInjected/{def_type}]",
                                     f"missing <{key}.{i}> (EN: {en_text!r})")
    return found


def main():
    ap = argparse.ArgumentParser(description="Validate mod translation files.")
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent,
                    help="repo root (default: parent of Scripts/)")
    ap.add_argument("--strict", action="store_true", help="treat warnings as errors")
    args = ap.parse_args()

    lang_roots = sorted(args.root.glob("*/Languages")) + \
                 ([args.root / "Languages"] if (args.root / "Languages").is_dir() else [])
    defs_dirs = sorted(args.root.glob("*/Defs")) + \
                ([args.root / "Defs"] if (args.root / "Defs").is_dir() else [])
    if not lang_roots:
        print(f"No Languages/ directory found under {args.root}", file=sys.stderr)
        return 2

    report = Report()
    sidecar = load_sidecar(args.root, report)
    if sidecar is None:
        return 2

    english_keyed = {}
    languages = []
    for lang_root in lang_roots:
        for lang_dir in sorted(p for p in lang_root.iterdir() if p.is_dir()):
            if lang_dir.name == "English":
                english_keyed.update(collect_keyed(lang_dir, report))
            else:
                languages.append(lang_dir)

    if not english_keyed:
        print("No English Keyed strings found; nothing to check against.", file=sys.stderr)
        return 2

    defs = collect_defs(defs_dirs, sidecar.active_packages)
    check_sidecar_freshness(defs, sidecar, report)
    found_by_lang = {}
    for lang_dir in languages:
        found_by_lang[lang_dir.name] = check_language(
            lang_dir, english_keyed, sidecar, report)

    # Cross-language parity: any DefInjected key one language translates
    # beyond the required set (secondary fields, extra collection elements)
    # must exist in every language — a key added in one pass and forgotten in
    # the others is exactly the drift this catches. Keys compare in
    # canonical (sidecar) spelling, so index-form and handle-form
    # translations of the same field cannot false-positive.
    union = {}
    for found in found_by_lang.values():
        for def_type, keys in found.items():
            union.setdefault(def_type, set()).update(keys)
    demanded = {}  # def_type -> required keys expanded to element form
    for def_type in sidecar.def_types:
        dem = demanded.setdefault(def_type, set())
        for key, entry in sidecar.required(def_type).items():
            dem.add(key)
            if entry.get("isCollection"):
                dem.update(f"{key}.{i}" for i in range(len(entry["english"])))
    for lang, found in sorted(found_by_lang.items()):
        for def_type, keys in sorted(union.items()):
            extra = keys - found.get(def_type, set()) \
                - demanded.get(def_type, set())
            extra = {k for k in extra
                     if not ({k.split(".")[-1], k.split(".")[-2] if
                              k.split(".")[-1].isdigit() else None}
                             & PARITY_EXEMPT_FIELDS)}
            for key in sorted(extra):
                report.error(f"[{lang}/DefInjected/{def_type}]",
                             f"missing <{key}> (translated in other languages)")

    for line in report.errors:
        print(f"ERROR   {line}")
    for line in report.warnings:
        print(f"WARNING {line}")
    checked = ", ".join(sorted({l.name for l in languages})) or "none"
    print(f"\n{len(english_keyed)} English keys; languages checked: {checked}")
    print(f"{len(report.errors)} error(s), {len(report.warnings)} warning(s)")
    return 1 if report.errors or (args.strict and report.warnings) else 0


if __name__ == "__main__":
    sys.exit(main())
